name: list_controller
description: Tools for creating list controllers. Supports infinite scroll, pagination, lazy loading, sorting, filtering, synchronization, huge lists, etc. Architecture and widgets agnostic.

version: 0.1.0
repository: https://github.com/astoniocom/list_controller
issue_tracker: https://github.com/astoniocom/list_controller/issues
homepage: https://github.com/astoniocom/list_controller

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  meta: ^1.3.0
  rxdart: ">=0.27.0 <0.29.0"

dev_dependencies:
  lints: ^2.0.0
  mockito: ^5.0.0
  test: ^1.16.0
